### ISSUE TITLE
Crashing Node after launching

### ISSUE THREAD

**Issue by Leonngm** [SICKAG/sick_safetyscanners2#13]
Hi,

we are having problems with a strange error: Immediately after executing the sick_safetyscanners2_launch.py file, the node crashes with the message: `[ERROR] [sick_safetyscanners2_node-1]: process has died [pid 900, exit code -11 ...]`

![crashing_node](https://user-images.githubusercontent.com/83963992/137188038-c8c41c6c-a05d-491b-9de7-e82c2d9c6d41.png)

This error seems related to #8 and the order in which the methods are called seems to be messed up. We alsp tried the lifecycle node from #11, since it solved the problem for them. The node also crashes after the activation of the lifecycle node.
Our setup looks like the following: 
microScan3 is connected to a router with an ethernet cable. Raspberry pi 4 is connected to the router with an ethernet cable and to a second router via wifi for internet access. We are able to ping the laser scanner from the raspberry pi. The laser scanner is working with a computer using your ROS 1 packages.
We are using ROS galactic and installed your packages the following (`sudo apt-get install ros-<rosdistro>-sick-safetyscanners2-interfaces
sudo apt-get install ros-<rosdistro>-sick-safetyscanners-base`  does not seem to work for ROS galactic as stated in #12  ):

1. Downloaded and installed the base (ros2 branch )following the instructions from: https://github.com/SICKAG/sick_safetyscanners_base
2. Downloaded the interfaces from: https://github.com/SICKAG/sick_safetyscanners2_interfaces into the colcon workspace.
3. Copied the base package into the colcon workspace.
4. colcon build
5. Followed the installation from source from: https://github.com/SICKAG/sick_safetyscanners2
6. Updating the IP adresses in the launch file accordingly.
7. colcon build again
8. Launching the node via the launch files.

Since you suggested to use gdp in #8, we also tried that, which gave use the following: 

![gdp_information](https://user-images.githubusercontent.com/83963992/137187820-c39e7555-2e44-4327-9751-c3dfc8f5afaf.png)

This error description does not look to promising. 

Do you have any ideas? Thanks in advance!

**Comment by Leonngm** [comment]
Hi, we are looking forward to test your code changes.

**Comment by Leonngm** [comment]
Are there any updates yet?
Maybe the issue is not because of the code, but because of the scanner configuration? Do we have to change anything when switching from ROS1 to ROS2?

**Comment by guilyx** [comment]
@Leonngm Is #15 helping ?

**Comment by galambosmisi** [comment]
Hi, we are having the exact same issue! As soon as I can I will test #15!

**Comment by Leonngm** [comment]
Hi all,
just yesterday i managed to solve the issue. It is exactly what you reported in #15. I managed to solve it by discarding the data packets until everything is configured, but i guess your solution is much more elegant. As soon as everything is running, it is working like a charm.
 Looking forward to test yours.

**Comment by puck-fzi** [comment]
Merged PR #15 

Closing this, as it should hopefully be fixed by this.
Thanks for the contribution and help in finding it.
