### ISSUE TITLE
Support for SICK TIM_7XXS

### ISSUE THREAD

**Issue by Yadunund** [SICKAG/sick_safetyscanners2#20]
Hi there,

I'm curious if this driver is meant to work with t he TIM_771S and other safety lidars? 

If not, what are the implementation files that need to be updated to extend support to this product variant? I'm interested in making some enhancements to the driver to support ROS 2 composition but unclear if I should target this driver or the ones in `sick_scan2`.

**Comment by puck-fzi** [comment]
Hi,

the TIMs are targeted in another repository, this driver is for the microScan3 family. So best target the corresponding sick scan repository.
