### ISSUE TITLE
ROS2 Support for S300 (mini)?

### ISSUE THREAD

**Issue by tonynajjar** [SICKAG/sick_safetyscanners2#21]
Hello, I just wanted to know if you plan to support the S300 (mini) with a ROS2 driver? How different would the driver be from the one for the currently supported hardware, if I decided to implement it myself? Thanks

**Comment by puck-fzi** [comment]
Hi, this driver targets the microScan3 family of drivers. The S300 has a different protocol it uses. So this driver will not support the S300.
There might be ROS2 drivers on github for the S300, however I am not aware of any officially released driver
