### ISSUE TITLE
Change /scan publisher frequency

### ISSUE THREAD

**Issue by jesusramondovale** [SICKAG/sick_safetyscanners2#34]
Hi! Can somebody tell me what part of the src code must be changed in order to get a different scan publisher frequency? (Currently 35Hz) 

Thank you!

**Comment by puck-fzi** [comment]
Hi, you could simply set the skip value in the launch file, this will then skip the amount of messages specified. Reducing the publishing frequency.

**Comment by jesusramondovale** [comment]
Thank you so much!!

**Comment by souravchandrasaha** [comment]
Currently I'm getting frequency of 35 hz . Is there any way to increase it ?

**Comment by nickoma90** [comment]
Hi, no, for these devices the scanning frequency cannot be adjusted.
