### ISSUE TITLE
New ROS2 release ?

### ISSUE THREAD

**Issue by doisyg** [SICKAG/sick_safetyscanners2#43]
Dear maintainers,
Is it possible to tag and release the latest version of the drivers ? I see many improvements that we would love to have and use from binaries since the last release in december 2021.

**Comment by puck-fzi** [comment]
Hi,
I will trigger a new release soon. It is planned for June in all current active distros

**Comment by YannickdeHoop** [comment]
any updates on a new Humble release?

**Comment by ruffsl** [comment]
Could we cut new releases for ROS 2 Iron and Jazzy as well?

**Comment by puck-fzi** [comment]
sick_safetyscanners_base release triggered for humble, iron, jazzy, and rolling.

Needs to be merged before the ros2 part can be released

**Comment by puck-fzi** [comment]
sick_safetyscanners_interfaces release triggered for jazzy and rolling.

Needs to be merged before the ros2 part can be released

**Comment by puck-fzi** [comment]
iron, humble and rolling are triggered.

jazzy is still waiting for a merge of the interfaces

**Comment by puck-fzi** [comment]
jazzy now triggered as well, will be included in the next syncs for each distro. 

Closing this
