### ISSUE TITLE
Need to merge 2 nanoscan3 

### ISSUE THREAD

**Issue by souravchandrasaha** [SICKAG/sick_safetyscanners2#47]
I have 2 nos nanoscan3 which placed apporx 1 meter apart. To cover entire 360 degree of AMR we placed it diagonally . How can we merge both topics of scan into one single topic?

**Comment by puck-fzi** [comment]
Hi, this driver does not provide functionality for this. However, there are different nodes out there that might achieve what you want. You could try: https://github.com/MSDRobotics/ira_laser_tools/tree/humble, (Disclaimer: I have not tested it myself, so I don't know if it will work)
