### ISSUE TITLE
GLS6

### ISSUE THREAD

**Issue by andreyvatoropinit** [SICKAG/sick_safetyscanners2#5]
https://www.sick.com/ag/en/localization-and-positioning-solutions/line-guidance-and-grid-localization/gls6/c/g507063

Hello! i have this model of camera. may somebody tell me, how is it possible to work with this device from Ubuntu ?

**Comment by puck-fzi** [comment]
Hi, this repository is for the ROS2 driver for the sick laserscanners family. Best ask the SICK Support directly. Maybe you find something in the download section of your link.
